version: '3'

services:
  web:
    build: ./users
    command: python user_management.py
    restart: always
    ports:
      - "8080:5000"



#    depends_on:
#      - sqlite3
#  
#  sqlite3:
#    image: nouchka/sqlite3:latest
  
  web1:
    build: ./rides
    command: python ride_management.py
    restart: always
    ports:
      - "8000:5000"

#    depends_on:
#      - sqlite3
